### ISSUE TITLE
"Printing to Screen" Wont Compile

### ISSUE THREAD

**Issue by Towtow10** [phil-opp/blog_os#323]
When trying to build after completing "Providing An Interface".
I recieve this error 

```thread 'rustc' panicked at 'assertion failed: !unsize', /checkout/src/librustc_typeck/check/mod.rs:2212
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `rust_os`.

To learn more, run the command again with --verbose.
make: *** [makefile:37: kernel] Error 101
```
With verbose:
```
thread 'rustc' panicked at 'assertion failed: !unsize', /checkout/src/librustc_typeck/check/mod.rs:2212
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `rust_os`.

Caused by:
  process didn't exit successfully: `rustc --crate-name rust_os src/lib.rs --crate-type staticlib --emit=dep-info,link -C debuginfo=2 -C metadata=1af3db583bd19e66 -C extra-filename=-1af3db583bd19e66 --out-dir /home/jacob/Documents/RustOS/target/x86_64-rust_os/debug/deps --target x86_64-rust_os -L dependency=/home/jacob/Documents/RustOS/target/x86_64-rust_os/debug/deps -L dependency=/home/jacob/Documents/RustOS/target/debug/deps --extern volatile=/home/jacob/Documents/RustOS/target/x86_64-rust_os/debug/deps/libvolatile-8f9a5138d9f58c33.rlib --extern rlibc=/home/jacob/Documents/RustOS/target/x86_64-rust_os/debug/deps/librlibc-bc7c07f4d6078d4f.rlib --extern spin=/home/jacob/Documents/RustOS/target/x86_64-rust_os/debug/deps/libspin-1433c0b45b26eec6.rlib --sysroot /home/jacob/.xargo` (exit code: 101)
make: *** [makefile:37: kernel] Error 101

```

**Comment by bjorn3** [comment]
Looks like issue https://github.com/rust-lang/rust/issues/41669
